name: Continuous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  JAVA_VERSION: '17'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: Compile
        run: sbt compile
  native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make cmake
      - name: Build and Install s2n-tls
        run: |
          git clone https://github.com/awslabs/s2n.git
          cd s2n
          cmake .
          make
          sudo make install
      - name: Build native binary
        run: sbt nativeLink
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: Check format
        run: sbt checkFormat
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:${{env.JAVA_VERSION}}
          apps: sbt
      - name: Scalafix Lint
        run: sbt scalafixLint
#  unit_test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: coursier/setup-action@v1
#        with:
#          jvm: temurin:${{env.JAVA_VERSION}}
#          apps: sbt
#      - name: Run tests with coverage Report
#        run: sbt testCoverage
#      - uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          fail_ci_if_error: true
